version: '3.7'

services:
  web:
    build: .
    ports: 
     - "9000:9000"
    networks:
      - backend
      
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    ports:
      - '6379:6379'

networks:
  backend: