version: '3.7'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    ports:
      - '6379:6379'

volumes:
  db_data: {}
networks:
  backend: