version: '3.7'

services:
  api-gateway:
    container_name: postblitz-api-gateway
    image: destructor98/postblitz-api-gateway
    restart: always
    env_file:
      - /home/destructor/Desktop/IT/Dev/PostBlitz/infrastructure/gateway.env
    ports:
      - "80:80"
    networks:
      - postblitz-network

  postblitz-user-service:
    container_name: postblitz-api-user
    image: destructor98/postblitz-api-user
    restart: always
    depends_on:
      - redis
    volumes:
      - ./data/server-logs:/usr/server/user/build/logs
    env_file:
      - /home/destructor/Desktop/IT/Dev/PostBlitz/infrastructure/secrets.env
    ports:
      - "9001:9001"
    networks:
      - postblitz-network

  postblitz-blog-service:
    container_name: postblitz-api-blog
    image: destructor98/postblitz-api-blog
    restart: always
    depends_on:
      - redis
    volumes:
      - ./data/server-logs:/usr/server/blog/build/logs
    env_file:
      - /home/destructor/Desktop/IT/Dev/PostBlitz/infrastructure/secrets.env
    ports:
      - "9003:9003"
    networks:
      - postblitz-network

  postblitz-admin-service:
    container_name: postblitz-api-admin
    image: destructor98/postblitz-api-admin
    restart: always
    depends_on:
      - redis
    volumes:
      - ./data/server-logs:/usr/server/admin/build/logs
    env_file:
      - /home/destructor/Desktop/IT/Dev/PostBlitz/infrastructure/secrets.env
    ports:
      - "9002:9002"
    networks:
      - postblitz-network

  redis:
    container_name: redis
    image: 'redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - postblitz-network

networks:
  postblitz-network:
    driver: bridge


