
GET http://localhost:9000/api/users

###

GET http://localhost:9000/api/users/id/USERID

###

GET http://localhost:9000/api/users/username/jphn777

###

POST http://localhost:9000/api/users/register
Content-Type: application/json

{
  "name": "John Doe",
  "username": "jphn777",
  "password": "johnIsHere",
  "email": "john777@gmail.com",
  "address": "Dublin",
  "pincode": "112233",
  "country": "Ireland"
}

###

POST http://localhost:9000/api/users/login
Content-Type: application/json

{
  "username": "jphn777",
  "password": "johnIsHere"
}

###

GET http://localhost:9000/api/blogs

###

GET http://localhost:9000/api/blogs/id/BLOGID

###

GET http://localhost:9000/api/blogs/title/BLOGTITLE

###

GET http://localhost:9000/api/blogs/category/BLOGCATEGORY

###

POST http://localhost:9000/api/blogs/create
Content-Type: application/json

{
  "title": "Blog 1",
  "author": "63728771a0f61112a4716c8f",
  "description": "This is blog 1",
  "content": "This is blog 1",
  "categories": ["sci-fi", "fantasy"],
  "shareLink": "sharelink"
}
