name: Building Servers

on:
  push:
    paths:
      - "server/user/**"
      - "server/blog/**"
      - "server/admin/**"

env:
  USER_VERSION: "2.0.0"
  BLOG_VERSION: "2.0.0"
  ADMIN_VERSION: "2.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Logging in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Building User Server
        if: ${{ contains(github.event.head_commit.modified, 'server/user/') }}
        run: |
          cd server/user
          docker buildx build --no-cache -t destructor98/postblitz-api-user:${{ env.USER_VERSION }} .
          env.USER_VERSION=$((env.USER_VERSION + 1))
          echo "USER_VERSION=${{ env.USER_VERSION }}" >> $GITHUB_ENV

      - name: Pushing User Server Image
        if: ${{ contains(github.event.head_commit.modified, 'server/user/') }}
        run: |
          docker push destructor98/postblitz-api-user:${{ env.USER_VERSION }}

      - name: Build Blog Server
        if: ${{ contains(github.event.head_commit.modified, 'server/blog/') }}
        run: |
          cd server/blog
          docker buildx build --no-cache -t destructor98/postblitz-api-blog:${{ env.BLOG_VERSION }} .
          env.BLOG_VERSION=$((env.BLOG_VERSION + 1))
          echo "BLOG_VERSION=${{ env.BLOG_VERSION }}" >> $GITHUB_ENV

      - name: Pushing Blog Server Image
        if: ${{ contains(github.event.head_commit.modified, 'server/blog/') }}
        run: |
          docker push destructor98/postblitz-api-blog:${{ env.BLOG_VERSION }}

      - name: Build Admin Server
        if: ${{ contains(github.event.head_commit.modified, 'server/admin/') }}
        run: |
          cd server/admin
          docker buildx build --no-cache -t destructor98/postblitz-api-admin:${{ env.ADMIN_VERSION }} .
          env.ADMIN_VERSION=$((env.ADMIN_VERSION + 1))
          echo "ADMIN_VERSION=${{ env.ADMIN_VERSION }}" >> $GITHUB_ENV

      - name: Pushing Admin Server Image
        if: ${{ contains(github.event.head_commit.modified, 'server/admin/') }}
        run: |
          docker push destructor98/postblitz-api-admin:${{ env.ADMIN_VERSION }}
