name: Building User Server

on:
  push:
    branches:
      - main
    paths:
      - "server/user/**"

jobs:
  serverBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pushing User Server Image as Latest
        uses: docker/build-push-action@v4
        with:
          context: ./server/user/
          push: true
          tags: destructor98/postblitz-api-user:latest
