name: Building User Server

on:
  push:
    branches:
      - main
    paths:
      - "server/user/**"

jobs:
  userBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app

      - name: Build and Push Image with GitHub SHA Tag
        uses: docker/build-push-action@v4
        with:
          context: ./server/user/
          push: true
          tags: |
            destructor98/postblitz-api-user:latest
            destructor98/postblitz-api-user:${{ github.sha }}
